const LABELS = {
  kuis: { text: 'Source by Kuis Kelas', cls: 'bg-ok/10 text-ok border-ok/30' },
  kisikisi: { text: 'Source by Kisi Kisi', cls: 'bg-tekad-red/10 text-tekad-red border-tekad-red/30' },
  ai: { text: 'Generated by AI', cls: 'bg-ink-soft/10 text-ink-soft border-ink-soft/25' },
  prediksi: { text: 'Prediksi dari materi', cls: 'bg-gold/10 text-gold border-gold/30' },
};

export default function SourceBadge({ sourceType, className = '' }) {
  const info = LABELS[sourceType] || LABELS.ai;
  return (
    <span
      className={`inline-block whitespace-nowrap rounded-full border text-[10px] font-bold px-2 py-0.5 ${info.cls} ${className}`}
    >
      {info.text}
    </span>
  );
}
